[package]
name = "clg"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]

[dependencies]
clap = "2.26"
env_logger = "0.4"
log = "0.3"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
url = "1.5"
